# Generated by Django 5.0.7 on 2024-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('access_code', models.CharField(max_length=1000)),
                ('reference', models.CharField(max_length=1000)),
                ('auth_url', models.CharField(max_length=10000)),
            ],
        ),
    ]
